export const prefixes = {
  aic: 'http://data.lblod.info/id/ai-components/',
  besluit: 'http://data.vlaanderen.be/ns/besluit#',
  dct: 'http://purl.org/dc/terms/',
  eli: 'http://data.europa.eu/eli/ontology#',
  'eli-dl': 'http://data.europa.eu/eli/eli-draft-legislation-ontology#',
  ext: 'http://mu.semte.ch/vocabularies/ext/',
  foaf: 'http://xmlns.com/foaf/0.1/',
  mandaat: 'http://data.vlaanderen.be/ns/mandaat#',
  oa: 'http://www.w3.org/ns/oa#',
  org: 'http://www.w3.org/ns/org#',
  prov: 'http://www.w3.org/ns/prov#',
  skos: 'http://www.w3.org/2004/02/skos/core#',
  xsd: 'http://www.w3.org/2001/XMLSchema#',
};
